kind: pipeline
name: default
type: docker
platform:
  os: linux
  arch: arm
steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: lgallet7/ipservice
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password