kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: lgallet7/ipservice
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password